type ISomeType = {[key: string]: any};
const categories:ISomeType = {
    countries: [
    "Japan",
    "United States",
    "Canada",
    "United Kingdom",
    "France",
    "Germany",
    "Italy",
    "Spain",
    "Australia",
    "Brazil",
    "Russia",
    "China",
    "South Korea",
    "North Korea",
    "India",
    "Mexico",
    "Indonesia",
    "South Africa",
    "Egypt",
    "Nigeria",
    "Saudi Arabia",
    "Iran",
    "Turkey",
    "Argentina",
    "Qatar",
    "Philippines",
    "Morocco",
    "Thailand",
    "Ukraine",
    "Poland",
    "Cambodia",
    "Qatar",
    "Vietnam",
    "Belgium",
    "Sweden",
    "Switzerland",
    "Norway",
    "Denmark",
    "Finland",
    "Romania",
    "Netherlands",
    "Portugal",
    "Greece",
    "Chile",
    "Czech Republic",
    "Slovakia",
    "Hungary",
    "Ireland",
    "Croatia",
    "Estonia",
    ],
    genres: [
    "Comedy",
    "Fantasy",
    "Crime",
    "Drama",
    "Music",
    "Adventure",
    "History",
    "Thriller",
    "Animation",
    "Family",
    "Mystery",
    "Biography",
    "Action",
    "Romance",
    "SciFi",
    "War",
    "Western",
    "Horror",
    "Musical",
    "Sport"
    ],
    films:[
    'The Shawshank Redemption',
    'The Godfather',
    'Pulp Fiction',
    'Inception',
    'The Matrix',
    'Zombieland',
    'Resident Evil',
    'Black Swan',
    'Requiem for a Dream'
    ],
    medicine: [
    "Schizophrenia",
    "Hemodialysis",
    "Cardiac massage",
    "Brain surgery",
    "Gastroscopy",
    "Gastroenteritis",
    "Diabetes",
    "High blood pressure",
    "Cancer treatment",
    "Bone fracture treatment",
    "Pneumonia",
    "Abdominal surgery",
    "Infectious disease",
    "Operating room",
    "Anesthesia",
    "Blood test",
    "Endoscopy",
    "Dental treatment",
    "Dermatology",
    "Radiation therapy",
    "Kidney transplant",
    "Blood coagulation",
    "Cardiac surgery",
    "eye surgery",
    "bone marrow transplant",
    "orthopedic surgery",
    "respiratory care",
    "radiologic diagnosis",
    "pregnancy test",
    "artificial ventilator",
    "heart attack",
    "infectious disease control",
    "cancer test",
    "life support system",
    "blood pressure measurement",
    "oxygen supply",
    "heart transplant",
    "cardiac catheterization",
    "peritoneal dialysis",
    "cardiopulmonary resuscitation",
    "thrombolytic therapy",
    "osteoporosis treatment",
    "percutaneous coronary intervention",
    "stress management",
    "emergency rescue",
    ],
    chemistry: [
    "Dihydrogenoxide",
    "Dehydrogenase",
    "Optical Absorption Spectroscopy",
    "Nuclear Magnetic Resonance Spectroscopy",
    "Gas Chromatography",
    "Mass spectrometry",
    
    "polymerization reaction",
    
    "electrophoresis",
    
    "molecular biology",
    
    "chemical reaction",
    
    "organic chemistry",
    
    "high performance liquid chromatography",
    
    "temperature controlled reaction",
    
    "precipitation reaction",
    
    "distillation",
    
    "hydrolysis",
    
    "oxidation reaction",
    
    "reduction reaction",
    
    "esterification reaction",]
}
export default categories;